# Site
repository: moredhel/resume
# favicon: images/favicon.ico

# Personal info
name: Hamish Hutchings
title: Cloud Native Consultant
email: moredhel@aoeu.me
website: https://aoeu.me/resume

# Social links
twitter_username: hamhut1066
github_username:  moredhel
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: veggiehutch
linkedin_username: hamish-hutchings-77466149
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
With a focus on Infrastructure automation, I also enjoy backend development. From CICD and programmable Infrastructure to microservices and Containerisation.

I live and breathe the cloud and want to help more people transition into today’s cloud-native ecosystem

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in programming languages and software engineering some of my other interests and hobbies include:
   - Rock climbing 🧗
   - Paragliding 🛩️
   - Reading 📖

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
